var envVars = {
    catList      : [],
    lifetimeList : []
};
var CNTXT_ = {
    owner:{
        id          : null,
        login       : null,
        password    : null,
        cookie_pass : null,
        auto_auth   : null,
        name        : null,
        s_name      : null,
        phone       : null,
        email       : null,
        send_mail   : null,
        img         : null,
        city_id     : null,
        region_id   : null,
        create_date : null,
        last_time   : null,
        rating      : null,
        rights      : null,
        vote_qt     : null,
        about_user  : null,
        web_site    : null,
        status      : null
    },
    speaker:{
        id          : null,
        login       : null,
        password    : null,
        cookie_pass : null,
        auto_auth   : null,
        name        : null,
        s_name      : null,
        phone       : null,
        email       : null,
        send_mail   : null,
        img         : null,
        city_id     : null,
        region_id   : null,
        create_date : null,
        last_time   : null,
        rating      : null,
        rights      : null,
        vote_qt     : null,
        about_user  : null,
        web_site    : null,
        status      : null
    },
    user:{
        id          : null,
        login       : null,
        password    : null,
        cookie_pass : null,
        auto_auth   : null,
        name        : null,
        s_name      : null,
        phone       : null,
        email       : null,
        send_mail   : null,
        img         : null,
        create_date : null,
        last_time   : null,
        rating      : null,
        rights      : null,
        vote_qt     : null,
        about_user  : null,
        web_site    : null,
        ws_token    : null
    },
    discus :{
        id              : null,
        sender_id       : null,
        consumer_id     : null,
        ads_id          : null,
        content         : null
    },
    review:{
        id          : null,
        sender_id   : null,
        consumer_id : null,
        star_qt     : null,
        favorite    : null,
        comment     : null,
        create_date : null
    },
    target_ads:{
        id          : null,
        ads_type    : null,
        user_id     : null,
        user_login  : null,
        user_rating : null,
        category    : null,
        active      : null,
        coord_x     : null,
        coord_y     : null,
        img         : null,
        description : null,
        cost        : null,
        crete_date  : null,
        min_x       : null,
        max_x       : null,
        min_y       : null,
        max_y       : null
    },
    target_msg         : null,
    user_reviews       : {},
    page_name          : null,
    ads_type           : null,
    ads_category       : null,
    ads_collection     : {},
    ads_owner_id       : null,
    messages           : null,
    date               : null,
    lifetime           : null,
    ws_token            : null,
    session            : null,
    float_data         : null,
    integer_data       : null,
    tmp                : null,
    have_sys_notify    : null,
    setting_page_data  : null,
    mode               : null,
    categories         : null
};